### ISSUE TITLE
Add-Migration "Initial" Not working

### ISSUE THREAD

**Issue by smilegse** [etrupja/DrinkAndGo#2]
I am a new comer of MVC Core. I am downloaded the project from github and can not add initial migration. please find error details:  **Add-Migration : Exception calling "AddFromFile" with "1" argument(s): "'basePath' cannot be an empty string ("")** 

I am using visual studio express 2017

Please help.

**Comment by mosageneral** [comment]
me too

**Comment by abiolakunle** [comment]
try `command
`dotnet ef add migrations Initial`
